//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int attendance_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int emp_id { get; set; }
        public string csv { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
