//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterion
    {
        public int cri_id { get; set; }
        public Nullable<double> cri_total_leave { get; set; }
        public Nullable<int> cri_sick_leave { get; set; }
        public Nullable<int> cri_earned_leave { get; set; }
        public Nullable<int> cri_casual_leave { get; set; }
        public Nullable<double> cri_short_leave { get; set; }
    }
}
