//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeave
    {
        public int emp_id { get; set; }
        public Nullable<double> total_leaves { get; set; }
        public Nullable<int> sick_leave { get; set; }
        public Nullable<int> earned_leave { get; set; }
        public Nullable<int> casual_leave { get; set; }
        public Nullable<double> short_leave { get; set; }
        public Nullable<double> remaining_leaves { get; set; }
    }
}
