//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int h_id { get; set; }
        public string h_name { get; set; }
        public Nullable<System.DateTime> hajj_from { get; set; }
        public Nullable<System.DateTime> hajj_to { get; set; }
        public string hajj_total { get; set; }
        public Nullable<int> hajj { get; set; }
        public Nullable<int> EidF { get; set; }
        public Nullable<int> EidAdha { get; set; }
        public Nullable<int> PakDay { get; set; }
        public Nullable<int> AzadiDay { get; set; }
        public Nullable<System.DateTime> eid_from { get; set; }
        public Nullable<System.DateTime> eid_to { get; set; }
        public Nullable<System.DateTime> eidAd_from { get; set; }
        public Nullable<System.DateTime> eidAd_to { get; set; }
    }
}
