//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIIT_HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int leave_id { get; set; }
        public string leave_type { get; set; }
        public Nullable<System.DateTime> date_from { get; set; }
        public Nullable<System.DateTime> date_to { get; set; }
        public string leave_description { get; set; }
        public int emp_id { get; set; }
        public string leave_status { get; set; }
        public string day_from { get; set; }
        public string day_to { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
